# --- Logging ---
logging.level.org.springframework=debug

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

# Defer running `data.sql` until after Hibernate has created/updated the schema
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false